{% set name = "flask-babel" %}
{% set version = "3.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flask_babel-{{ version }}.tar.gz
  sha256: be015772c5d7f046f3b99c508dcf618636eb93d21b713b356db79f3e79f69f39

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.7,<4.0
    - pip
    - poetry-core

  run:
    - python >=3.7,<4.0
    - babel >=2.11.0,<3.0.0
    - flask >=2.0.0,<3.0.0
    - jinja2 >=3.1.2,<4.0.0
    - pytz >=2022.7,<2023.0

test:
  imports:
    - flask_babel
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/python-babel/flask-babel
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Adds i18n/l10n support to Flask applications
  dev_url: https://github.com/python-babel/flask-babel

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
