{% set name = "Flask-Babel" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f9faf45cdb2e1a32ea2ec14403587d4295108f35017a7821a2b1acb8cfd9257d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools

  run:
    - python >=3.7
    - flask <3
    - babel >=2.3
    - jinja2 >=2.5

test:
  imports:
    - flask_babel

about:
  home: https://github.com/python-babel/flask-babel
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Adds i18n/l10n support to Flask applications
  dev_url: https://github.com/python-babel/flask-babel

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
