{% set name = "Flask-Babel" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f3e8687e470ab896f18e86e7faa787f1725a0e8d9469572719e46a262d941f2f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7,<4.0
    - setuptools
    - flask
    - babel >=2.3
    - jinja2 >=2.5

  run:
    - python >=3.7,<4.0
    - flask
    - babel >=2.3
    - jinja2 >=2.5
    - pytz >=2022.7,<2023.0

test:
  imports:
    - flask_babel
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/python-babel/flask-babel
  license_file: LICENSE
  license: BSD-3-Clause
  license_family: BSD
  summary: Adds i18n/l10n support to Flask applications
  dev_url: https://github.com/python-babel/flask-babel

extra:
  recipe-maintainers:
    - pmlandwehr
    - xylar
